services:
  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - 9092:9092

  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
